CardiologistV2/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CardiologistV2.Models;
using CardiologistV2.DAL;

namespace CardiologistV2.Controllers
{
    public class HistoryController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        //
        // GET: /History/

        public ActionResult Index()
        {
            return View(db.Histories.ToList());
        }

        //
        // GET: /History/Details/5

        public ActionResult Details(int id = 0)
        {
            History history = db.Histories.Find(id);
            if (history == null)
            {
                return HttpNotFound();
            }
            return View(history);
        }

        //
        // GET: /History/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /History/Create

        [HttpPost]
        public ActionResult Create(History history)
        {
            if (ModelState.IsValid)
            {
                db.Histories.Add(history);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(history);
        }

        //
        // GET: /History/Edit/5

        public ActionResult Edit(int id = 0)
        {
            History history = db.Histories.Find(id);
            if (history == null)
            {
                return HttpNotFound();
            }
            return View(history);
        }

        //
        // POST: /History/Edit/5

        [HttpPost]
        public ActionResult Edit(History history)
        {
            if (ModelState.IsValid)
            {
                db.Entry(history).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(history);
        }

        //
        // GET: /History/Delete/5

        public ActionResult Delete(int id = 0)
        {
            History history = db.Histories.Find(id);
            if (history == null)
            {
                return HttpNotFound();
            }
            return View(history);
        }

        //
        // POST: /History/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            History history = db.Histories.Find(id);
            db.Histories.Remove(history);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CardiologistV2/Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CardiologistV2.Models;
using CardiologistV2.DAL;
using WebMatrix.WebData;
using CardiologistV2.Matlab.DomainModels;

namespace CardiologistV2.Controllers
{
    public class RecordController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        //
        // GET: /Record/

        public ActionResult Index()
        {
            var records = db.Records.Include(r => r.patients);
            return View(records.ToList());
        }

        //
        // GET: /Record/Details/5

        public ActionResult Details(int id = 0)
        {
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        //
        // GET: /Record/Create

        public ActionResult Create()
        {
            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Name");
            return View();
        }

        //
        // POST: /Record/Create

        [HttpPost]
        public ActionResult Create(Record record, HttpPostedFileBase txtfile)
        {
            if (ModelState.IsValid)
            {
                string filename = ""; string path = ""; string Data="";
                if (txtfile != null && txtfile.ContentLength > 0)
                {
                    filename = System.Guid.NewGuid() + "_" + txtfile.FileName;
                    path = Server.MapPath("~/Signals/" + filename);
                    txtfile.SaveAs(path);
                    //   record.Data = filename;
                    Data = System.IO.File.ReadAllText(path);
                    record.Data = Data;
                    
                }
                #region Filter File
                string path1 = Server.MapPath("~/Matlab");
                System.IO.File.WriteAllText(path1 + "\\" + filename, Data);
                MLApp.MLApp matlab = new MLApp.MLApp();
                matlab.Execute("cd('" + path1 + "')");
                matlab.Execute("a=load('" + filename + "')");
                matlab.Execute("c=baselinefilter(a," + 370 + ")");
                var o = (double[,])matlab.GetVariable("c", "base");
                string filedata = "";

                for (int i = 0; i < o.GetLength(0); i++)
                {
                    for (int j = 0; j < o.GetLength(1); j++)
                    {
                        filedata += o[i, j] + " ";
                    }
                    filedata.Trim(' ');

                    filedata += "\n";
                }
                #endregion //DONE!
                
                #region Pass File to Feature Extractor
                ECG ecgFeatureExtractor = new ECG();
              string InputVector = ecgFeatureExtractor.ExtractFeatures(filedata, filename, 370); // fs = 370
                string filename2="feat.txt";
              System.IO.File.WriteAllText(path1 + "\\" + filename2, InputVector);
                #endregion

             
               #region simulate network
                matlab.Execute("b = load ('" + filename2 +"')");
                matlab.Execute("n = load('matlab.mat')");
                matlab.Execute("s = sim(n.net ,b)");
               var obj = (double[,])matlab.GetVariable("s", "base");
                #endregion

              /* #region Make Logical Decision
               int MaxIndex = -1;
               int numpulses = obj.GetLength(1);
               int numpvc = 0; int numlbbb = 0; int numrbbb = 0; int numnormal = 0;
               var vector = new List<double>();
               for (int j = 0; j < numpulses; j++)
               {
                  // for (int i = 0; i < obj.GetLength(0); i++)
                   for (int i = 0; i < 4; i++)
                   {
                       vector.Add(obj[i, j]);
                   }
                   MaxIndex = vector.IndexOf(vector.Max());
                   switch (MaxIndex)
                   {
                       case 0: //pvc
                           numpvc++;
                           break;
                       case 1: //lbbb
                           numlbbb++;
                           break;
                       case 2: //rbbb
                           numrbbb++;
                           break;
                       case 3: //normal
                           numnormal++;
                           break;
                       default:
                           break;
                   }
               }
               string result = "Pvc = " + ((double)(numpvc * 100) / numpulses )+ "%" + "Lbbb = "
     + ((double)(numlbbb * 100) / numpulses )+ "% " + "Rbbb = "
      + ((double)(numrbbb * 100) / numpulses )+ "% " + "Normal = "
      + ((double)(numnormal * 100) / numpulses )+ "%";

               //string result = "Pvc = " + numpvc + "lbbb = " + numlbbb + "rbbb =" + numrbbb + "normal = " + numnormal;
               #endregion
                */
               #region other result
               int non = 0;
               int nol = 0;
               int nor = 0;
               int nop = 0;
               for (int i = 0; i < obj.GetLength(1); i++)
               {
                   double maxx = -1;
                   for (int j = 0; j < 4; j++)
                   {
                       if (obj[0, i] >= maxx)
                       {
                           maxx = obj[0, i];
                       }
                       if (obj[1, i] >= maxx)
                       {
                           maxx = obj[1, i];
                       }
                       if (obj[2, i] >= maxx)
                       {
                           maxx = obj[2, i];
                       }
                       if (obj[3, i] >= maxx)
                       {
                           maxx = obj[3, i];
                       }
                       if (obj[0, i] == maxx)
                           nop++;
                       if (obj[1, i] == maxx)
                           nol++;
                       if (obj[2, i] == maxx)
                           nor++;
                       if (obj[3, i] == maxx)
                           non++;
                   }
               }
               string resultt = "Pvc = " + nop + "lbbb = " + nol + "rbbb =" + nor + "normal = " + non;
            /*   string resultt = "Pvc = " + (double)((nop * 100) / obj.GetLength(0)) + "%" + "Lbbb = "
    + (double)((nol * 100) / obj.GetLength(0)) + "% " + "Rbbb = "
     + (double)((nor * 100) / obj.GetLength(0))+ "% " + "Normal = "
     + (double)((non * 100) / obj.GetLength(0)) + "%";*/
               #endregion
                   record.Result = resultt;
                //int PatientID = WebSecurity.GetUserId(User.Identity.Name); 
                //Patient patient = db.Patients.Find(record.PatientID);
                int pid = 0;
                foreach (Patient pa in db.Patients)
                {
                    if (pa.Name == User.Identity.Name)
                    { pid = pa.PatientID; }
                }
                
                record.PatientID = pid;
                db.Records.Add(record);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Name", record.PatientID);
            return View(record);
        }

        //
        // GET: /Record/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Name", record.PatientID);
            return View(record);
        }

        //
        // POST: /Record/Edit/5

        [HttpPost]
        public ActionResult Edit(Record record)
        {
            if (ModelState.IsValid)
            {
                db.Entry(record).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Name", record.PatientID);
            return View(record);
        }

        //
        // GET: /Record/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        //
        // POST: /Record/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Record record = db.Records.Find(id);
            db.Records.Remove(record);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CardiologistV2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
<title>@ViewBag.Title - Medical </title>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Medical Theme Css Template</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="~/Content/Site.css" media="screen" />
<script language="javascript" src="scripts/browserdetect_lite.js" type="text/javascript"></script>
<script language="javascript" src="scripts/opacity.js" type="text/javascript"></script>
 @Styles.Render("~/Content/css")
 @Scripts.Render("~/bundles/modernizr")
</head>

<body>
<div id="main_container">
	<div class="header">
    	<div id="logo"><a href="index.html"><img src="~/Content/images/OurLogo2.gif" alt="" title="" width="200" height="100" border="0" /></a></div>
    
    	<div class="right_header">
            <div class="float-right">
            @Html.Partial("_LoginPartial")
            </div>
            <div id="menu">
                <ul>                                              
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    @*<li><a href="#" title="">Services</a></li>*@
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        
        </div>
    
    </div>
    
    
    <div id="middle_box">
    	<div class="middle_box_content"><img src="~/Content/images/banner_content.jpg" alt="" title="" /></div>
    </div>
    
    
    <div class="pattern_bg">
    
    	<div class="pattern_box">
            <div class="pattern_box_icon"><img src="~/Content/images/icon1.png" alt="" title="" width="70" height="112" /></div>
            <div class="pattern_content">
            <h1>Future <span class="blue">Medicine</span></h1>
            <p class="pat">
            Online diagnosis of ECG records taking advantage of the expertise of many cardiologist.
            </p>
            </div>
        </div>
        
        
    	<div class="pattern_box">
            <div class="pattern_box_icon"><img src="~/Content/images/icon2.png" alt="" title="" width="70" height="112" /></div>
            <div class="pattern_content">
            <h1>All <span class="blue"> your records at one place</span></h1>
            <p class="pat">
            Your entire archive can be studied by experienced cardiologist.
            </p>
            </div>
        </div>        
        
    
    </div>
    
    <div id="main_content">
    
 			<div class="box_content">
					<div class="box_title">
                    	<div class="title_icon"><img src="~/Content/images/mini_icon1.gif" alt="" title="" /></div>
                        
                        <h2>You Can<span class="dark_blue">@if (User.IsInRole("Patient")){@Html.ActionLink("Add a Record", "Create","Record")}</span></h2>
                    </div>
                    
                    <div class="box_text_content">
                    	<img src="~/Content/images/calendar.gif" alt="" title="" class="box_icon" />
                        <div class="box_text">
                        Keeping your records in one place
                        </div>
                      @*  <a href="#" class="details">+ details</a>*@
                    </div>

                    <div class="box_text_content">
                    	<img src="~/Content/images/calendar.gif" alt="" title="" class="box_icon" />
                        <div class="box_text">
                        You can review your past recordings to check up the updates.
                        </div>
                      @*  <a href="#" class="details">+ details</a>*@
                    </div>
	
            </div>
            
            
 			<div class="box_content">
					<div class="box_title">
                    	<div class="title_icon"><img src="~/Content/images/mini_icon2.gif" alt="" title="" /></div>
                        <h2>You Can<span class="dark_blue">@if (User.IsInRole("Patient")){@Html.ActionLink("Add Your Medical History", "Create","History")}@if (User.IsInRole("Doctor")) { @Html.ActionLink("Check Who Asked For Your Advice", "Index","Consultation")}</span></h2>
                    </div>
                    
                    <div class="box_text_content">
                    	<img src="~/Content/images/checked.gif" alt="" title="" class="box_icon" />
                        <div class="box_text">
                        Scan and upload your most recent records.
                        </div>
                      @*  <a href="#" class="details">+ details</a>*@
                    </div>

                    <div class="box_text_content">
                    	<img src="~/Content/images/checked.gif" alt="" title="" class="box_icon" />
                        <div class="box_text">
                        
                        </div>
                       @* <a href="#" class="details">+ details</a>*@
                    </div>
	
            </div>            
            
            
  			<div class="box_content">
					<div class="box_title">
                    	<div class="title_icon"><img src="~/Content/images/mini_icon3.gif" alt="" title="" /></div>
                        <h2>You Can<span class="dark_blue">@if (User.IsInRole("Patient")){@Html.ActionLink("Ask a Doctor !", "Create","Consultation")}</span></h2>
                    </div>
                    
                    <div class="box_text_content">
                    	<img src="~/Content/images/checked.gif" alt="" title="" class="box_icon" />
                        <div class="box_text">
                        The most talented specialists gathered in one place to serve our patients.
                        </div>
                       @* <a href="#" class="details">+ details</a>*@
                    </div>

                    <div class="box_text_content">
                    	<img src="~/Content/images/checked.gif" alt="" title="" class="box_icon" />
                        <div class="box_text">
                       Ask them for free consultation !
                        </div>
                        @*<a href="#" class="details">+ details</a>*@
                    </div>
	
            </div>           
            
            
            
            
            
            
            
            
            
         
            
            
        <div class="clear"></div>    
       </div>     
     <div id="down_content">
    <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>        
            
     <div id="footer">
     	<div class="copyright">
        @*<img src="~/Content/images/OurLogo2.gif" alt="" title="" width="160" height="70" />*@
        </div>
        <div class="center_footer">&copy; Cardiologist 2015. All Rights Reserved</div>
    	<div class="footer_links">
        <a href="http://csstemplatesmarket.com"><img src="~/Content/images/OurLogo2.gif" alt="csstemplatesmarket" title="csstemplatesmarket" border="0" width="120" height="40" /></a>
        </div>
    
    
    </div>



</div>
    
        @Scripts.Render("~/bundles/jquery")
        @*RenderSection("scripts", required: false)*@
        @if (IsSectionDefined("scripts"))
        {
            @RenderSection("scripts")
        }  
</body>
</html>